### ISSUE TITLE
Request for re-establish automation to push new releases to github

### ISSUE THREAD

**Issue by romvarg** [networknt/light-scheduler#87]
It appears that there was some automation in place up until version 2.1.9 that regularly pushed new release builds to Docker Hub (https://hub.docker.com/r/networknt/light-scheduler)

however, since then it looks like there have been no new releases of docker images pushed out.

would it be possible please to request to reinstate that automation?  Thanks!

**Comment by stevehu** [comment]
I had an issue with the docker image and didn't notice that. A new version 2.1.27 has been pushed to the Docker Hub. Thanks a lot for your help. 

https://hub.docker.com/repository/docker/networknt/light-scheduler/general

**Comment by romvarg** [comment]
awesome - speedy response, thank You!
