### ISSUE TITLE
version 2.1.28 is not avaiable

### ISSUE THREAD

**Issue by kangroowl** [networknt/light-scheduler#93]
@stevehu   I saw there is 2.1.28 version in the changelog.  We got an error when pulling it.   Has it been published?   Does it include the vulnerbility fixes?  

![image (23)](https://github.com/networknt/light-scheduler/assets/14826339/18ed0a96-6da0-4a9c-ade2-291642d93394)

**Comment by kangroowl** [comment]
@stevehu  Any updates on the 2.1.28 image?  We tried the 2.1.27 image.   But we got the following error and could not start the server.  Was there any change between 2.1.9 to 2.1.27 can casue this? 

04:08:57,924 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3d121db3 - Registering current configuration as safe fallback point

Failed to start server:null

**Comment by stevehu** [comment]
I did a manual release of 2.1.28. It should be there now. Will add it to the light-bot config to release it automatically in the future. Thanks.
