### ISSUE TITLE
The restAPIs do not return correct http status in some cases

### ISSUE THREAD

**Issue by kangroowl** [networknt/light-scheduler#96]
During our test,  we found the restAPI returns 500 instead of 404 when the client tries to delete a non-existing schedule.  500 is a server error.   The client cannot tell if the delete failed is becasue a server error or the schedule does not exist.  The update rest API should also return 404 on non-existing schedule.  Another minor thing is that the update API returns 201 instead of 200 when success.

**Comment by stevehu** [comment]
I agree that we should return 404. Do you have the stacktrace available? Or the steps to reproduce it? Thanks.

**Comment by kangroowl** [comment]
@stevehu We just used a curl cmd and got 500 back.  

HTTP/2 500 
server: L
content-type: application/json
content-length: 0
date: Tue, 28 Nov 2023 18:05:20 GMT

**Comment by kangroowl** [comment]
We also found to reschedule to a different frequency,  we have to delete and recreate the schedule.  I would be nice if the update API can handle this on its own.    When the delete succeeds but the recreate fails,  the client is left in a situation that the original schedule is gone.

**Comment by stevehu** [comment]
When you receive the 500 status code, there must be an error with stacktrace on the server. Could you please capture that? The update is a good idea, and I think it is doable.

**Comment by kangroowl** [comment]
@stevehu  This is the stacktrace:
19:56:42.217 [XNIO-1 task-3]  3qst0eCTTnG_BYh_q1OHeg DEBUG c.n.s.handler.SchedulersGetHandler:85 getClusterDefinition - found one address in the collection 10.254.33.175:8443
19:56:42.218 [XNIO-1 task-3]  3qst0eCTTnG_BYh_q1OHeg DEBUG c.n.s.handler.SchedulersGetHandler:128 getLocalDefinitions - The number of definitions at local is 0
19:56:42.218 [XNIO-1 task-3]  3qst0eCTTnG_BYh_q1OHeg DEBUG c.n.s.handler.SchedulersGetHandler:85 getClusterDefinition - found one address in the collection 10.254.27.218:8443
19:56:42.318 [XNIO-1 task-3]   ERROR io.undertow.server.Connectors:431 executeRootHandler - UT005071: Undertow request failed HttpServerExchange{ POST /schedulers}
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
	at com.networknt.status.Status.shouldShowMessage(Status.java:239)
	at com.networknt.status.Status.toStringConditionally(Status.java:274)
	at com.networknt.handler.LightHttpHandler.setExchangeStatus(LightHttpHandler.java:140)
	at com.networknt.handler.LightHttpHandler.setExchangeStatus(LightHttpHandler.java:73)
	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:92)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by kangroowl** [comment]
Another unrelated old problem.  We see the duplicate messages issue again.  This time we made sure the topic was created before the services were started.   The schedule definition is every 5 mins.  The scheduler fires a dozen messages for it every second.   After restarting the service pods,  the problem is gone.    I verified there is only one task definition for this schecduled task by using the Get RestAPI.  Any clue what can cause this?  I cannot figure out based on my understanding of the code. Not sure if it is related to kafka producer config.

**Comment by kangroowl** [comment]
@stevehu   Is there any plan to fix the above issues?

**Comment by kangroowl** [comment]
@stevehu   Do you have an esitmate when the restAPI reponse code issue can be fixed?   We are hitting the issue. The client side cannot tell what happened when the 500 status is returned.

**Comment by stevehu** [comment]
I have reviewed the issue again but couldn't find any root cause. The error stack posted above should only happen for an older version. If you upgrade to the latest version, it should be OK.

**Comment by kangroowl** [comment]
Close this as fixed.  Thanks!
